[general]
import = [
  "~/.config/alacritty/solarized_dark.toml",
]

[env]
# To be compatible with my zshrc (__setup_ssh_agent)
TERM_PROFILE = "Personal"

[window]
dimensions = { lines = 125, columns = 240 }

[font]
# To find available fonts, run `fc-list : family`
normal = { family = "AnonymicePro Nerd Font" }
size = 16
# Less compact rendering identical to iTerm2
offset = { x = 1 }

[selection]
save_to_clipboard = true
semantic_escape_chars = "$=,│`|:\"' ()[]{}<>\t"

[[keyboard.bindings]]
key = "Period"
mods = "Command"
chars = "\u001B."

[[keyboard.bindings]]
key = "F13"
chars = "\u001B[1;2P"
